---
abstract: 'utilities to find English pangrams'
author:
  - 'Jesse Sheidlower <jester@panix.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Pangram
no_index:
  directory:
    - t
    - inc
requires:
  List::MoreUtils: 0
  Test::More: 0
version: 0.01
